const profiles = [
    {
        _id: "1",
        name: "Aisha Bello",
        gender: "Female",
        image: "https://plus.unsplash.com/premium_vector-1740447965951-d1645e4422d7?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwbHVzLWZlZWR8MjN8fHxlbnwwfHx8fHw%3D",
        address: "12 Palm Street",
        city: "Lagos",
        phone: "08012345678",
        description: "Professional housekeeper with 5 years of experience.",
        work: "Full-time",
        email: "aisha.bello@example.com",
        title: "Housekeeper",
        category: "HouseKeeper", // Added category
    },
    {
        _id: "2",
        name: "David Okafor",
        gender: "Male",
        image: "https://plus.unsplash.com/premium_vector-1740447965951-d1645e4422d7?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwbHVzLWZlZWR8MjN8fHxlbnwwfHx8fHw%3D",
        address: "34 Crescent Rd",
        city: "Abuja",
        phone: "08087654321",
        description: "Skilled driver with 10+ years of experience in safe driving.",
        work: "Part-time",
        email: "david.okafor@example.com",
        title: "Driver",
        category: "Driver", // Added category
    },
    {
        _id: "3",
        name: "Grace Adeyemi",
        gender: "Female",
        image: "https://via.placeholder.com/150",
        address: "7 Lekki Phase 1",
        city: "Lagos",
        phone: "08123456789",
        description: "Experienced nanny specializing in childcare for toddlers.",
        work: "Full-time",
        email: "grace.adeyemi@example.com",
        title: "Nanny",
        category: "Nanny", // Added category
    },
    {
        _id: "4",
        name: "Emeka Johnson",
        gender: "Male",
        image: "https://via.placeholder.com/150",
        address: "42 Market Street",
        city: "Enugu",
        phone: "08187654321",
        description: "Expert gardener with a passion for landscaping.",
        work: "Contract",
        email: "emeka.johnson@example.com",
        title: "Gardener",
        category: "Gardner", // Added category
    },
    {
        _id: "5",
        name: "Fatima Suleiman",
        gender: "Female",
        image: "https://plus.unsplash.com/premium_vector-1740447965951-d1645e4422d7?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwbHVzLWZlZWR8MjN8fHxlbnwwfHx8fHw%3D",
        address: "22 Ring Road",
        city: "Kano",
        phone: "08099887766",
        description: "Home cook specializing in African and continental dishes.",
        work: "Full-time",
        email: "fatima.suleiman@example.com",
        title: "Cook",
        category: "Cook", // Added category
    },
    {
        _id: "6",
        name: "Samuel Ekong",
        gender: "Male",
        image: "https://via.placeholder.com/150",
        address: "15 Victoria Island",
        city: "Lagos",
        phone: "08111222333",
        description: "Security expert with military background.",
        work: "Night shift",
        email: "samuel.ekong@example.com",
        title: "Security Guard",
        category: "Security Guard", // Added category
    },
    {
        _id: "7",
        name: "Linda Uche",
        gender: "Female",
        image: "https://via.placeholder.com/150",
        address: "8 Admiralty Way",
        city: "Port Harcourt",
        phone: "09022334455",
        description: "Caring and patient elderly caregiver with nursing experience.",
        work: "Full-time",
        email: "linda.uche@example.com",
        title: "Caregiver",
        category: "Caregiver", // Added category
    },
    {
        _id: "8",
        name: "Tunde Adebayo",
        gender: "Male",
        image: "https://plus.unsplash.com/premium_vector-1740447965951-d1645e4422d7?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwbHVzLWZlZWR8MjN8fHxlbnwwfHx8fHw%3D",
        address: "19 Yaba Road",
        city: "Ibadan",
        phone: "07033221144",
        description: "Laundry expert skilled in fabric care.",
        work: "Part-time",
        email: "tunde.adebayo@example.com",
        title: "Laundry Attendant",
        category: "Laundry Attendant", // Added category
    },
    {
        _id: "9",
        name: "Zainab Mohammed",
        gender: "Female",
        image: "https://via.placeholder.com/150",
        address: "5 Airport Road",
        city: "Kaduna",
        phone: "08044556677",
        description: "Efficient and organized personal assistant.",
        work: "Full-time",
        email: "zainab.mohammed@example.com",
        title: "Personal Assistant",
        category: "Babysitter", // Added category
    },
    {
        _id: "10",
        name: "Peter Obi",
        gender: "Male",
        image: "https://via.placeholder.com/150",
        address: "32 Independence Ave",
        city: "Awka",
        phone: "07099887744",
        description: "Dedicated nanny with over 8 years of experience.",
        work: "Full-time",
        email: "peter.obi@example.com",
        title: "Nanny",
        category: "Nanny", // Added category
    },
    {
        _id: "11",
        name: "Jessica Ayodeji",
        gender: "Female",
        image: "https://via.placeholder.com/150",
        address: "25 High Street",
        city: "Benin",
        phone: "08055667788",
        description: "Housekeeper with attention to detail and hygiene.",
        work: "Part-time",
        email: "jessica.ayodeji@example.com",
        title: "Housekeeper",
        category: "HouseKeeper", // Added category
    },
    {
        _id: "12",
        name: "Ahmed Yusuf",
        gender: "Male",
        image: "https://via.placeholder.com/150",
        address: "9 Stadium Road",
        city: "Jos",
        phone: "08166778899",
        description: "Experienced private driver with VIP client service.",
        work: "Full-time",
        email: "ahmed.yusuf@example.com",
        title: "Driver",
        category: "Driver", // Added category
    },
    {
        _id: "13",
        name: "Mariam Ali",
        gender: "Female",
        image: "https://via.placeholder.com/150",
        address: "15 Borno Road",
        city: "Maiduguri",
        phone: "08077889900",
        description: "Laundry specialist with eco-friendly techniques.",
        work: "Part-time",
        email: "mariam.ali@example.com",
        title: "Laundry Attendant",
        category: "Laundry Attendant", // Added category
    },
    {
        _id: "14",
        name: "Chris Nwosu",
        gender: "Male",
        image: "https://via.placeholder.com/150",
        address: "4 Ikorodu Road",
        city: "Lagos",
        phone: "07066554433",
        description: "Gardener with expertise in tropical plants.",
        work: "Full-time",
        email: "chris.nwosu@example.com",
        title: "Gardener",
        category: "Gardner", // Added category
    },
    {
        _id: "15",
        name: "Rose Obinna",
        gender: "Female",
        image: "https://via.placeholder.com/150",
        address: "50 Allen Avenue",
        city: "Lagos",
        phone: "08055667722",
        description: "Personal assistant skilled in scheduling and travel planning.",
        work: "Full-time",
        email: "rose.obinna@example.com",
        title: "Personal Assistant",
        category: "Babysitter", // Added category
    },
    {
        _id: "16",
        name: "Ibrahim Lawal",
        gender: "Male",
        image: "https://via.placeholder.com/150",
        address: "23 GRA",
        city: "Ilorin",
        phone: "07044556633",
        description: "Security guard with 12 years of experience.",
        work: "Night shift",
        email: "ibrahim.lawal@example.com",
        title: "Security Guard",
        category: "Security Guard", // Added category
    },
    {
        _id: "17",
        name: "Stella Chukwu",
        gender: "Female",
        image: "https://via.placeholder.com/150",
        address: "14 Maitama",
        city: "Abuja",
        phone: "08199887766",
        description: "Professional cook with a background in hotel catering.",
        work: "Full-time",
        email: "stella.chukwu@example.com",
        title: "Cook",
        category: "Cook", // Added category
    },
];

export default profiles;


